name: example
description: A flutterwave example project.

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutterwave_standard:
    path: "../"
#  flutterwave_standard: ^1.0.3
  cupertino_icons: ^1.0.6
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true
